# Generated by Django 5.1.7 on 2025-04-10 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0002_profile_role'),
        ('RestaurantApp', '0002_restaurant'),
    ]

    operations = [
    ]
