# Generated by Django 5.1.7 on 2025-04-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0010_delete_emailotp_alter_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='is_active',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
