# Generated by Django 5.1.7 on 2025-04-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0011_remove_restaurant_is_active_restaurant_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine_type',
            field=models.CharField(choices=[('Indian', 'Indian'), ('Chinese', 'Chinese'), ('Italian', 'Italian'), ('Mexican', 'Mexican'), ('Thai', 'Thai'), ('Japanese', 'Japanese'), ('Multiple', 'Multiple')], max_length=100),
        ),
    ]
