# Merged migration: Generated by Django on manual merge

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0002_profile_role'),
        ('RestaurantApp', '0002_restaurant'),
    ]

    operations = [
        # This is a merge migration so it doesn't need operations unless you want to add something manually.
    ]

